tasks:
  - init: npm install

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - johnsoncodehk.volar
    - antfu.vite
    - syler.sass-indented
