name: 'Build/release'

on: [push, pull_request, workflow_dispatch]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v3

      - name: 'Install Node.js, NPM and Yarn'
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build Electron App'
        run: npm run app:build

      - name: Move Distribution Files
        run: sh ./move-dist.sh

      - run: echo ${{ matrix.os }}

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-${{ github.sha }}
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: macos-${{ github.sha }}
          path: dist-mac

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: windows-${{ github.sha }}
          path: dist-win
